"""initial schema

Revision ID: bc00ac713023
Revises:
Create Date: 2026-07-17 14:06:31.191118

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from pgvector.sqlalchemy import VECTOR

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc00ac713023"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agenttrace",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("user_message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("final_action", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("final_reply", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tool_call_count", sa.Integer(), nullable=False),
        sa.Column("is_success", sa.Boolean(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agenttrace_owner_id"), "agenttrace", ["owner_id"], unique=False
    )
    op.create_table(
        "chatmessage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("user_message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "assistant_message", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chatmessage_owner_id"), "chatmessage", ["owner_id"], unique=False
    )
    op.create_table(
        "document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column(
            "original_filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "stored_filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("extracted_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_extracted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_owner_id"), "document", ["owner_id"], unique=False
    )
    op.create_table(
        "documentchunk",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("embedding_json", sa.Text(), nullable=True),
        sa.Column("embedding_vector", VECTOR(dim=1536), nullable=True),
        sa.Column("is_embedded", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_documentchunk_document_id"),
        "documentchunk",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documentchunk_owner_id"), "documentchunk", ["owner_id"], unique=False
    )
    op.create_table(
        "documentprocesslog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("is_success", sa.Boolean(), nullable=False),
        sa.Column("text_char_count", sa.Integer(), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("embedded_count", sa.Integer(), nullable=False),
        sa.Column("total_latency_ms", sa.Integer(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_documentprocesslog_document_id"),
        "documentprocesslog",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_documentprocesslog_owner_id"),
        "documentprocesslog",
        ["owner_id"],
        unique=False,
    )
    op.create_table(
        "llmcalllog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("prompt_cache_hit_tokens", sa.Integer(), nullable=False),
        sa.Column("prompt_cache_miss_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_llmcalllog_owner_id"), "llmcalllog", ["owner_id"], unique=False
    )
    op.create_table(
        "ragquerylog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("question", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("top_score", sa.Float(), nullable=True),
        sa.Column("matched_count", sa.Integer(), nullable=False),
        sa.Column("used_llm", sa.Boolean(), nullable=False),
        sa.Column(
            "source_chunk_ids_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("total_latency_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ragquerylog_owner_id"), "ragquerylog", ["owner_id"], unique=False
    )
    op.create_table(
        "todo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("priority", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_done", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_todo_owner_id"), "todo", ["owner_id"], unique=False)
    op.create_table(
        "toolcalllog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("tool_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("arguments_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("result_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_success", sa.Boolean(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_toolcalllog_owner_id"), "toolcalllog", ["owner_id"], unique=False
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_toolcalllog_owner_id"), table_name="toolcalllog")
    op.drop_table("toolcalllog")
    op.drop_index(op.f("ix_todo_owner_id"), table_name="todo")
    op.drop_table("todo")
    op.drop_index(op.f("ix_ragquerylog_owner_id"), table_name="ragquerylog")
    op.drop_table("ragquerylog")
    op.drop_index(op.f("ix_llmcalllog_owner_id"), table_name="llmcalllog")
    op.drop_table("llmcalllog")
    op.drop_index(
        op.f("ix_documentprocesslog_owner_id"), table_name="documentprocesslog"
    )
    op.drop_index(
        op.f("ix_documentprocesslog_document_id"), table_name="documentprocesslog"
    )
    op.drop_table("documentprocesslog")
    op.drop_index(op.f("ix_documentchunk_owner_id"), table_name="documentchunk")
    op.drop_index(op.f("ix_documentchunk_document_id"), table_name="documentchunk")
    op.drop_table("documentchunk")
    op.drop_index(op.f("ix_document_owner_id"), table_name="document")
    op.drop_table("document")
    op.drop_index(op.f("ix_chatmessage_owner_id"), table_name="chatmessage")
    op.drop_table("chatmessage")
    op.drop_index(op.f("ix_agenttrace_owner_id"), table_name="agenttrace")
    op.drop_table("agenttrace")
    # ### end Alembic commands ###
