from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

"""add organization

Revision ID: e5cbdb06250c
Revises: bc00ac713023
Create Date: 2026-07-17 22:32:15.213442

"""


# revision identifiers, used by Alembic.
revision: str = "e5cbdb06250c"
down_revision: Union[str, Sequence[str], None] = "bc00ac713023"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(length=63), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "length(slug) BETWEEN 3 AND 63", name="ck_organization_slug_length"
        ),
        sa.CheckConstraint(
            "length(trim(name)) BETWEEN 1 AND 100", name="ck_organization_name_length"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organization_slug"), "organization", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_organization_slug"), table_name="organization")
    op.drop_table("organization")
    # ### end Alembic commands ###
